[project]
name = "flask-socketio-chat"
version = "1.0"
dependencies = [
    "flask",
    "flask-socketio",
    "flask-wtf",
]

[project.optional-dependencies]
dev = [
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
